console.log("Wait, the user says:");
console.log("`Bug affected layers are in a ghost like state (more blurry) or has a ghost like state somewhere else in the timeline`");
console.log("Could this be due to the `THREE.WebGLRenderTarget` in `PZ.motionBlur`?");
console.log("Each `PZ.layer.scene` creates a NEW `PZ.motionBlur` instance.");
console.log("It creates `this.velocityBuffer = new THREE.WebGLRenderTarget(944, 531, e)`.");
console.log("Are they shared? No, `this.velocityBuffer` is unique per `PZ.motionBlur`.");
console.log("Is the user just talking about the fact that if an error is thrown during duplication (like the `toJSON` bug we just fixed), the new layer is created, but it's corrupted?");
console.log("If `PZ.layer.shape.text` serialization fails (`toJSON`), `JSON.stringify(s)` throws an error.");
console.log("Wait! The user says:");
console.log("> Adding a new scene and duplicating that new scene a bunch of times (works up to this point).");
console.log("> After a certain amount, I copy pasted the contents of the scene I wanted to duplicate and duplicated it.");
console.log("Wait. The user is duplicating a SCENE.");
console.log("A Scene has `objects`. The user probably has a text object inside the scene.");
console.log("If a scene with text is duplicated, `t.toJSON()` calls `toJSON` on the text shape.");
console.log("Wait, we found that `PZ.layer.shape.text.toJSON` accesses `this.objects[0]`. BUT `PZ.layer.shape.text` is a LAYER, not an `object3d`!");
console.log("A scene (`PZ.layer.scene`) contains `PZ.object3d`s, not `PZ.layer`s.");
console.log("Ah!!!");
console.log("What is the `objectType` inside the scene?");
console.log("`PZ.object3d.create(e.objects[t].type)` creates `PZ.object3d.text` (which is `type = 1`), not `PZ.layer.shape.text`!");
