console.log("Wait, if every duplicate creates new ThreeJS objects...");
console.log("Then `PZ.motionBlur` correctly tracks them using `this.prevModelViewMatrix` mapped to those UNIQUE `THREE.Object3D`s.");
console.log("Wait... what if a NEW object uses a previous matrix?");
console.log("Ah, `this.prevModelViewMatrix` uses `e` (`THREE.Object3D`) as the key in the `WeakMap`.");
console.log("If `PZ.motionBlur` uses a `WeakMap`, the keys are `THREE.Object3D`s. If they are NEW objects, they get NEW entries in the `WeakMap`.");
console.log("Wait, does `PZ.motionBlur` share `velocityBuffer` or `velocityShader` across different `PZ.layer.scene`?");
console.log("No, `this.velocityBuffer = new THREE.WebGLRenderTarget()`");
console.log("`this.velocityShader = new THREE.ShaderMaterial()`");
console.log("These are allocated inside `PZ.motionBlur.prototype.load` which is called per instance.");
console.log("Are `PZ.motionBlur` instances shared?");
console.log("In `PZ.layer.scene.prototype.load`: `this.motionBlur = new PZ.motionBlur(this)`.");
console.log("So NO, they are NOT shared.");
console.log("Wait... 'ghost like state (more blurry)'...");
console.log("What if the user is referring to the WebGL context memory issues when you duplicate too many scenes?");
console.log("If a scene allocates a `WebGLRenderTarget` (e.g. `this.velocityBuffer`), and many scenes are duplicated, we will run out of VRAM.");
console.log("When VRAM runs out, the GPU starts failing allocations, returning empty/black textures or just reusing memory, which causes 'ghosts' of other buffers to appear!");
console.log("Yes! If VRAM allocations fail silently, WebGL textures will contain random uninitialized data or data from previous frames.");
console.log("If the user says 'has a ghost like state somewhere else in the timeline', this means VRAM is exhausted and `velocityBuffer` or `pass.renderTarget` is corrupted.");
console.log("How to fix the memory leak?");
console.log("We already found that `PZ.layer.scene.prototype.unload` does NOT call `this.motionBlur.unload()` or `this.pass.dispose()`!");
console.log("Wait! Does `PZ.layer.scene` call `this.envMap.unload()`?");
